apiVersion: batch/v1
kind: Job
metadata:
  name: init-mockserver
spec:
  template:
    metadata:
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        # Add your init scripts below
        - >
          tar -xvf /regression-test-files/files.tar.gz &&
          . ./$TEST_DIRECTORY/reset-verify-mockserver.sh &&
          . ./$TEST_DIRECTORY/resource-resolution/init-mockserver.sh &&
          . ./$TEST_DIRECTORY/remote-ansible/init-mockserver.sh &&
          . ./$TEST_DIRECTORY/ansible-python-dg/init-mockserver.sh
        image: registry-dev.nso.lab-services.ca/nso-platform-onap-cds-regression-image:latest
        name: init-mockserver
        resources: {}
        volumeMounts:
          - name: regression-test-files
            mountPath: /regression-test-files
        env:
          - name: TEST_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: regression-env
                key: TEST_DIRECTORY
          - name: MOCKSERVER_URL
            valueFrom:
              configMapKeyRef:
                name: regression-env
                key: MOCKSERVER_URL
      restartPolicy: Never
      volumes:
        - name: regression-test-files
          configMap:
            name: regression-test-files
status: {}
